-- Seed initial data for Technical Regulations Inspections

-- Insert default admin user
-- Note: This user will need to be created in Supabase Auth first
-- The email should match the one in your Supabase Auth users table
INSERT INTO users (
    id,
    email,
    role,
    first_name,
    last_name,
    mfa_enabled,
    created_at,
    updated_at
) VALUES (
    '9b84eb25-85a5-48b1-a946-087e3bfbd913', -- Replace with actual Supabase Auth user ID
    'rudvel@gmail.com',
    'admin',
    'Admin',
    'User',
    true,
    NOW(),
    NOW()
);

-- Insert default integrations
INSERT INTO integrations (name, enabled, config_json, created_at, updated_at) VALUES
('email', true, '{"provider": "resend", "from_email": "triapp@mccaa.org.mt"}', NOW(), NOW()),
('google_maps', false, '{"api_key": "", "enabled": false}', NOW(), NOW()),
('safety_gate', true, '{"endpoint": "https://ec.europa.eu/safety-gate/api", "live_mode": true}', NOW(), NOW()),
('nando', true, '{"cache_enabled": true, "cache_duration_hours": 24}', NOW(), NOW()),
('icsms', true, '{"export_only": true, "push_enabled": false}', NOW(), NOW()),
('sentiment_ai', true, '{"model_version": "v1.0", "enabled": true}', NOW(), NOW()),
('azure_ad', false, '{"enabled": false, "tenant_id": "", "client_id": ""}', NOW(), NOW());

-- Insert Malta public holidays for 2024
INSERT INTO holidays_mt (holiday_date, description, is_recurring, created_at) VALUES
('2024-01-01', 'New Year''s Day', true, NOW()),
('2024-03-29', 'Good Friday', false, NOW()),
('2024-03-31', 'Easter Sunday', false, NOW()),
('2024-04-01', 'Easter Monday', true, NOW()),
('2024-05-01', 'Worker''s Day', true, NOW()),
('2024-06-07', 'Sette Giugno', true, NOW()),
('2024-06-29', 'St. Peter & St. Paul', true, NOW()),
('2024-08-15', 'Assumption of Mary', true, NOW()),
('2024-09-08', 'Our Lady of Victories', true, NOW()),
('2024-09-21', 'Independence Day', true, NOW()),
('2024-12-08', 'Immaculate Conception', true, NOW()),
('2024-12-13', 'Republic Day', true, NOW()),
('2024-12-25', 'Christmas Day', true, NOW()),
('2024-12-26', 'Boxing Day', true, NOW());

-- Insert Malta public holidays for 2025
INSERT INTO holidays_mt (holiday_date, description, is_recurring, created_at) VALUES
('2025-01-01', 'New Year''s Day', true, NOW()),
('2025-04-18', 'Good Friday', false, NOW()),
('2025-04-20', 'Easter Sunday', false, NOW()),
('2025-04-21', 'Easter Monday', true, NOW()),
('2025-05-01', 'Worker''s Day', true, NOW()),
('2025-06-07', 'Sette Giugno', true, NOW()),
('2025-06-29', 'St. Peter & St. Paul', true, NOW()),
('2025-08-15', 'Assumption of Mary', true, NOW()),
('2025-09-08', 'Our Lady of Victories', true, NOW()),
('2025-09-21', 'Independence Day', true, NOW()),
('2025-12-08', 'Immaculate Conception', true, NOW()),
('2025-12-13', 'Republic Day', true, NOW()),
('2025-12-25', 'Christmas Day', true, NOW()),
('2025-12-26', 'Boxing Day', true, NOW());

-- Insert default report templates
INSERT INTO report_templates (name, description, format, template_content, mapping_json, version, is_default, is_active, created_at, updated_at) VALUES
(
    'Standard Inspection Report',
    'A comprehensive template for detailed inspection reports',
    'html',
    '<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .section { margin: 20px 0; }
        .footer { margin-top: 40px; text-align: center; font-style: italic; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{title}}</h1>
        <p>Inspection ID: {{inspection_id}}</p>
        <p>Date: {{inspection_date}}</p>
    </div>
    
    <div class="section">
        <h2>Operator Information</h2>
        <p><strong>Name:</strong> {{operator_name}}</p>
        <p><strong>Address:</strong> {{operator_address}}</p>
        <p><strong>VAT Number:</strong> {{vat_number}}</p>
    </div>
    
    <div class="section">
        <h2>Inspection Details</h2>
        <p><strong>Inspector:</strong> {{inspector_name}}</p>
        <p><strong>Status:</strong> {{inspection_status}}</p>
        <p><strong>Findings:</strong></p>
        <ul>
            {{#each findings}}
            <li>{{this}}</li>
            {{/each}}
        </ul>
    </div>
    
    <div class="footer">
        <p>{{footer}}</p>
    </div>
</body>
</html>',
    '{
        "title": "Technical Regulations Inspection Report",
        "sections": [
            "inspection_details",
            "operator_information", 
            "checklist_results",
            "findings",
            "notices_issued",
            "recommendations"
        ],
        "footer": "This report was generated by TRIAPP"
    }',
    '1.0.0',
    true,
    true,
    NOW(),
    NOW()
),
(
    'Executive Summary Report',
    'A concise template for executive-level inspection summaries',
    'html',
    '<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .section { margin: 20px 0; }
        .footer { margin-top: 40px; text-align: center; font-style: italic; }
        .risk-high { color: #d32f2f; font-weight: bold; }
        .risk-medium { color: #f57c00; font-weight: bold; }
        .risk-low { color: #388e3c; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{title}}</h1>
        <p>Executive Summary</p>
    </div>
    
    <div class="section">
        <h2>Overview</h2>
        <p>{{overview}}</p>
    </div>
    
    <div class="section">
        <h2>Key Findings</h2>
        <ul>
            {{#each key_findings}}
            <li>{{this}}</li>
            {{/each}}
        </ul>
    </div>
    
    <div class="section">
        <h2>Risk Assessment</h2>
        <p><span class="risk-{{risk_level}}">Risk Level: {{risk_level}}</span></p>
        <p>{{risk_description}}</p>
    </div>
    
    <div class="section">
        <h2>Actions Required</h2>
        <ul>
            {{#each actions_required}}
            <li>{{this}}</li>
            {{/each}}
        </ul>
    </div>
    
    <div class="footer">
        <p>{{footer}}</p>
    </div>
</body>
</html>',
    '{
        "title": "Inspection Executive Summary",
        "sections": [
            "overview",
            "key_findings",
            "risk_assessment",
            "actions_required"
        ],
        "footer": "Executive summary generated by TRIAPP"
    }',
    '1.0.0',
    false,
    true,
    NOW(),
    NOW()
);

-- Insert sample product categories (for future use)
-- These would typically be managed through the admin interface
INSERT INTO economic_operators (name, vat_number, email, address, phone, created_at, updated_at) VALUES
(
    'Sample Electronics Retailer Ltd',
    'MT12345678',
    'info@sampleelectronics.mt',
    '123 Republic Street, Valletta VLT 1117, Malta',
    '+356 2123 4567',
    NOW(),
    NOW()
),
(
    'Test Import Company',
    'MT87654321', 
    'contact@testimport.com',
    '456 Merchants Street, Valletta VLT 1177, Malta',
    '+356 2123 7654',
    NOW(),
    NOW()
);

-- Insert sample checklist for testing
INSERT INTO checklists (
    id,
    name,
    description,
    json_schema,
    version,
    status,
    created_by,
    created_at,
    updated_at
) VALUES (
    '00000000-0000-0000-0000-000000000002',
    'General Product Safety Inspection',
    'Standard checklist for general product safety inspections under GPSR',
    '{
        "metadata": {
            "version": "1.0.0",
            "title": "General Product Safety Inspection",
            "description": "Standard checklist for general product safety inspections under GPSR",
            "legalBasis": "General Product Safety Regulation (EU) 2023/988"
        },
        "questions": [
            {
                "id": "q1",
                "type": "text",
                "title": "Product Name and Description",
                "description": "Provide the full name and detailed description of the product",
                "required": true,
                "validation": {
                    "minLength": 5,
                    "maxLength": 500
                },
                "legalRefs": [
                    {
                        "act": "GPSR",
                        "article": "Article 4",
                        "description": "Product identification requirements"
                    }
                ]
            },
            {
                "id": "q2",
                "type": "boolean",
                "title": "CE Mark Present",
                "description": "Is the CE marking visibly and legibly affixed to the product?",
                "required": true,
                "legalRefs": [
                    {
                        "act": "GPSR",
                        "article": "Article 30",
                        "description": "CE marking requirements"
                    }
                ]
            },
            {
                "id": "q3",
                "type": "photo",
                "title": "CE Mark Photo",
                "description": "Take a clear photo of the CE marking",
                "required": true,
                "conditional": {
                    "conditions": [
                        {
                            "questionId": "q2",
                            "operator": "equals",
                            "value": true
                        }
                    ],
                    "operator": "AND"
                },
                "validation": {
                    "minPhotos": 1,
                    "maxPhotos": 3
                }
            },
            {
                "id": "q4",
                "type": "single_choice",
                "title": "Product Category",
                "description": "Select the most appropriate product category",
                "required": true,
                "options": [
                    {
                        "id": "electronics",
                        "label": "Electronics and Electrical Equipment",
                        "value": "electronics"
                    },
                    {
                        "id": "toys",
                        "label": "Toys and Games",
                        "value": "toys"
                    },
                    {
                        "id": "textiles",
                        "label": "Textiles and Clothing",
                        "value": "textiles"
                    },
                    {
                        "id": "cosmetics",
                        "label": "Cosmetics and Personal Care",
                        "value": "cosmetics"
                    },
                    {
                        "id": "other",
                        "label": "Other",
                        "value": "other"
                    }
                ]
            },
            {
                "id": "q5",
                "type": "multi_choice",
                "title": "Safety Documentation Available",
                "description": "Which safety documentation is available for this product?",
                "required": false,
                "options": [
                    {
                        "id": "manual",
                        "label": "User Manual",
                        "value": "manual"
                    },
                    {
                        "id": "certificate",
                        "label": "Safety Certificate",
                        "value": "certificate"
                    },
                    {
                        "id": "declaration",
                        "label": "Declaration of Conformity",
                        "value": "declaration"
                    },
                    {
                        "id": "test_report",
                        "label": "Test Report",
                        "value": "test_report"
                    },
                    {
                        "id": "none",
                        "label": "No Documentation Available",
                        "value": "none"
                    }
                ]
            }
        ]
    }',
    '1.0.0',
    'published',
    '00000000-0000-0000-0000-000000000001',
    NOW(),
    NOW()
);

-- Update the checklist to be published by admin
UPDATE checklists 
SET status = 'published', 
    published_by = '00000000-0000-0000-0000-000000000001',
    updated_at = NOW()
WHERE id = '00000000-0000-0000-0000-000000000002';
